"""empty message

Revision ID: ca9e092d06c0
Revises: 
Create Date: 2022-07-01 11:37:25.375546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "ca9e092d06c0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authority",
        sa.Column("authority_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("authority_id"),
    )
    op.create_index(op.f("ix_authority_name"), "authority", ["name"], unique=True)
    op.create_table(
        "raw_seq",
        sa.Column("ga4gh", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.String(length=4000000000).with_variant(mysql.LONGTEXT(), "mysql"), nullable=False),
        sa.PrimaryKeyConstraint("ga4gh"),
    )
    op.create_table(
        "seq",
        sa.Column("seq_id", sa.Integer(), nullable=False),
        sa.Column("md5", sa.String(length=32), nullable=False),
        sa.Column("ga4gh", sa.String(length=32), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("circular", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("seq_id"),
    )
    op.create_index(op.f("ix_seq_ga4gh"), "seq", ["ga4gh"], unique=True)
    op.create_index(op.f("ix_seq_md5"), "seq", ["md5"], unique=False)
    op.create_table(
        "seq_type",
        sa.Column("seq_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("seq_type_id"),
    )
    op.create_index(op.f("ix_seq_type_name"), "seq_type", ["name"], unique=True)
    op.create_table(
        "molecule",
        sa.Column("molecule_id", sa.Integer(), nullable=False),
        sa.Column("seq_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("authority_id", sa.Integer(), nullable=True),
        sa.Column("seq_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["authority_id"],
            ["authority.authority_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seq_id"],
            ["seq.seq_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seq_type_id"],
            ["seq_type.seq_type_id"],
        ),
        sa.PrimaryKeyConstraint("molecule_id"),
        sa.UniqueConstraint("id", "authority_id", name="molecule_uix_id_authority"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("molecule")
    op.drop_index(op.f("ix_seq_type_name"), table_name="seq_type")
    op.drop_table("seq_type")
    op.drop_index(op.f("ix_seq_md5"), table_name="seq")
    op.drop_index(op.f("ix_seq_ga4gh"), table_name="seq")
    op.drop_table("seq")
    op.drop_table("raw_seq")
    op.drop_index(op.f("ix_authority_name"), table_name="authority")
    op.drop_table("authority")
    # ### end Alembic commands ###
